### ISSUE TITLE
422 - declaration failed

### ISSUE THREAD

**Issue by Yacho1998** [F5Networks/f5-ipam-controller#165]
**Setup Details**
 FIC Version : 0.1.11
 CIS Version : 2.18    
 FIC Build: f5networks/f5-ipam-controller:latest
 CIS Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 17.1.1.3      
 AS3 Version: 3.51      
 Orchestration: K8S/OSCP      
 Orchestration Version: 1.28            
 Additional Setup details: cilium

#### Description  
When updating the serviceAddress in TransportServer, a 422 error occurs, but there is no error when the configuration is first applied.

#### Steps To Reproduce
1)Here's my CIS config 
```
        - --ipam=true
        - --custom-resource-mode=true
        - --bigip-username=$(BIGIP_USERNAME)
        - --bigip-password=$(BIGIP_PASSWORD)
        - --bigip-url=10.9.89.236:443
        - --bigip-partition=kubernetes
        - --pool-member-type=cluster
        - --insecure
        - --log-level=DEBUG
```
2)Here's my TransportServer config
```
apiVersion: cis.f5.com/v1
kind: TransportServer
metadata:
  annotations:
  labels:
    f5cr: "true"
  name: ts-nginx-test1
  namespace: kube-system
spec:
  bigipRouteDomain: 0
  ipamLabel: Default
  mode: standard
  pool:
    monitor:
      interval: 20
      timeout: 10
      type: tcp
    service: nginx-test1
    serviceNamespace: default
    servicePort: 80
  snat: auto
  type: tcp
  virtualServerPort: 8081
```
3)I want to enable VIP(virtual address) route advertisement, so I updated the TransportServer configuration as follows:
```
apiVersion: cis.f5.com/v1
kind: TransportServer
metadata:
  annotations:
  labels:
    f5cr: "true"
  name: ts-nginx-test1
  namespace: kube-system
spec:
  bigipRouteDomain: 0
  ipamLabel: Default
  mode: standard
  serviceAddress：
  - routeAdvertisement: enable
  pool:
    monitor:
      interval: 20
      timeout: 10
      type: tcp
    service: nginx-test1
    serviceNamespace: default
    servicePort: 80
  snat: auto
  type: tcp
  virtualServerPort: 8081
```

#### Expected Result 
virtual address route advertisement enabled

#### Actual Result  
Response from BIG-IP: code: 422 --- tenant:kubernetes --- message: declaration failed

#### Diagnostic Information

When checking the logs in /var/log/ltm on the VE, I saw an error indicating that the virtual address already exists.

#### Observations (if any)

/var/log/ltm:
Dec  1 22:21:16 f5-test.cloud.onecloud.io err mcpd[6098]: 0107176c:3: Invalid Virtual Address, the IP address 10.9.249.100 already exists.
